apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-rcjrhkkd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-rcjrhkkd 
  name: go-rcjrhkkd
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-rcjrhkkd
    weight: 100 
